In [1]:
import numpy as np
import pandas as pd

In [2]:
# Importing Iris dataset to dataframe

df = pd.read_csv("iris.csv")

In [3]:
# Removing non-meaningful data from dataset

columns = df.columns.tolist()
dtypes = df.dtypes.to_dict()

for keys in dtypes:
    if dtypes[keys] == object:
        columns.remove(keys)

In [4]:
# Basic function to split dataset

def train_test_split(x,y,n):
    
    if n >1:
        n /= 100
        
    m = len(y)
    mTop = round(m*n)
    mBottom = m-mTop
    
    x_train = x.head(mTop).to_numpy()
    x_test = x.tail(mBottom).to_numpy()
    y_train = y.head(mTop).to_numpy()
    y_test = y.tail(mBottom).to_numpy()
    
    return x_train, x_test, y_train, y_test


In [5]:
# Dividing dataset in to part

df = df[columns]
print(columns)

column = input("Enter name of column from below list:   ")
y = df[column]
x = df.drop([column], axis=1)


['sepal.length', 'sepal.width', 'petal.length', 'petal.width']
Enter name of column from below list:   sepal.length


In [6]:
n = float(input("Enter how much data you want to use for train purpose:   "))

Enter how much data you want to use for train purpose:   .79


In [7]:
# Taking output from function

a,b,c,d = train_test_split(x,y,n)

In [8]:
a

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [9]:
b

array([[2.6, 6.9, 2.3],
       [2.2, 5. , 1.5],
       [3.2, 5.7, 2.3],
       [2.8, 4.9, 2. ],
       [2.8, 6.7, 2. ],
       [2.7, 4.9, 1.8],
       [3.3, 5.7, 2.1],
       [3.2, 6. , 1.8],
       [2.8, 4.8, 1.8],
       [3. , 4.9, 1.8],
       [2.8, 5.6, 2.1],
       [3. , 5.8, 1.6],
       [2.8, 6.1, 1.9],
       [3.8, 6.4, 2. ],
       [2.8, 5.6, 2.2],
       [2.8, 5.1, 1.5],
       [2.6, 5.6, 1.4],
       [3. , 6.1, 2.3],
       [3.4, 5.6, 2.4],
       [3.1, 5.5, 1.8],
       [3. , 4.8, 1.8],
       [3.1, 5.4, 2.1],
       [3.1, 5.6, 2.4],
       [3.1, 5.1, 2.3],
       [2.7, 5.1, 1.9],
       [3.2, 5.9, 2.3],
       [3.3, 5.7, 2.5],
       [3. , 5.2, 2.3],
       [2.5, 5. , 1.9],
       [3. , 5.2, 2. ],
       [3.4, 5.4, 2.3],
       [3. , 5.1, 1.8]])

In [10]:
c

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7])

In [11]:
d

array([7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4,
       7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8, 6.8,
       6.7, 6.7, 6.3, 6.5, 6.2, 5.9])