# Array using Numpy

In [1]:
import numpy as np

In [2]:
# Array with specific datatype --> np.array([values],dtype="s")
array1 = np.array([1,2,3,4,5,6,7,8])
print(array1)

[1 2 3 4 5 6 7 8]


In [3]:
# Array of specific range
arr = np.arange(10,31,2)
print(arr)


[10 12 14 16 18 20 22 24 26 28 30]


In [4]:
import time

# method 1
list1 = [i for i in range(10000000)]
list2 = [i for i in range(10000000,20000000)]
list3 = []
start = time.time()
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
t1 = time.time()-start
print(t1)

# method 2
arr1 = np.arange(10000000)
arr2 = np.arange(10000000,20000000)
start = time.time()
arr3 = arr1+arr2
t2 = time.time()-start
print(t2)
efficiency = t1/t2
print(efficiency)

2.8735532760620117
0.015629053115844727
183.85971656522204


## Numpy functions

##### Append

In [5]:
# On pressing shift+tab we get all info regarding that function
# np.append(array,value)
arr = np.append(arr,99)
print(arr)



[10 12 14 16 18 20 22 24 26 28 30 99]


##### Insert

In [6]:
# np.insert(array,index,value)
arr = np.insert(arr,5,67)
print(arr)

[10 12 14 16 18 67 20 22 24 26 28 30 99]


##### Delete

In [7]:
# np.delete(array,index)
arr = np.delete(arr,7)
print(arr)

[10 12 14 16 18 67 20 24 26 28 30 99]


## 2 D Array (matrix)

In [8]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Traversing 2D array

In [9]:
# array[row index,column index]
print(mat[0,1])

2


## 3D Array

In [10]:
mat3d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(mat3d)
print(mat3d[1,0,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
11
